sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 2468136zc
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: cqwm-yyhy
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
  wechat:
    appid: ${WX_APP_ID}
    secret: ${WX_APP_SECRET}
#    mchid: 1561414331
#    mchSerialNo: 4=================================6
#    privateKeyFilePath: D:\pay\apiclient_key.pem
#    apiV3Key: CZBK51236435wxpay435434323FFDuv3
#    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
#    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
#    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess
