sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 2468136zc
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: cqwm-yyhy
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
